name: NPM Audit

concurrency:
  group: ci-${{ github.ref }}-audit
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  workflow_call:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'
  merge_group:
    types: [checks_requested]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup
        uses: ./tools/github-actions/setup
      - name: Audit
        id: audit
        uses: ./tools/github-actions/audit
        with:
          severity: critical
          allWorkspaces: true
          recursive: true
          environment: all
      - name: Summary
        if: success() || failure()
        run: echo "${{ steps.audit.outputs.reportMarkdown }}" >> $GITHUB_STEP_SUMMARY

